project_id = "wfthvovlhphnrodrqxqt"

[functions.leads-collector]
verify_jwt = false

[functions.generate-blog]
verify_jwt = false

[functions.chat-storo]
verify_jwt = false

[functions.storo-billing-invoice]
verify_jwt = false